name: Send Message

on:
  workflow_dispatch:
  schedule:
    - cron: "0 05-23/3 * * *"

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Create appstate.json
        run: |
          export APPSTATE='${{ secrets.APPSTATE }}'
          echo $APPSTATE > appstate.json

      - name: Install dependencies
        run: npm ci

      - name: Run script
        run: |
          export THREAD_ID=${{ secrets.THREAD_ID }}  
          npm run send
